version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: carboneye_postgres
    restart: always
    environment:
      POSTGRES_USER: carboneye
      POSTGRES_PASSWORD: carboneye_pass
      POSTGRES_DB: carboneye_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-seed:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: carboneye_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
