export const SIRI_CONSTANTS = {
  // Pesos Máximos
  PESO_MAX_VEGETACAO: 45,
  PESO_MAX_HISTORICO: 30,
  PESO_MAX_INCENDIOS: 20,
  PESO_MAX_CLIMA: 5,

  // Saúde da Vegetação Atual (Limiares de NDVI/EVI)
  VEGETACAO_OTIMA: 0.8,
  VEGETACAO_BOA: 0.7,
  VEGETACAO_REGULAR: 0.6,
  VEGETACAO_ATENCAO: 0.5,
  VEGETACAO_CRITICA: 0.4,

  // Pontuações para Vegetação Atual
  PONTUACAO_VEGETACAO_OTIMA: 45,
  PONTUACAO_VEGETACAO_BOA: 40,
  PONTUACAO_VEGETACAO_REGULAR: 35,
  PONTUACAO_VEGETACAO_ATENCAO: 25,
  PONTUACAO_VEGETACAO_CRITICA: 15,

  // Penalidade de Estresse Hídrico
  LIMIAR_NDWI_ESTRESSE: -0.1,
  PENALIDADE_NDWI: 5,

  // Tendência Histórica (Variação Percentual)
  HISTORICO_CRESCIMENTO_ALTO: 10,
  HISTORICO_CRESCIMENTO_MEDIO: 5,
  HISTORICO_QUEDA_MEDIA: -5,
  HISTORICO_QUEDA_ALTA: -10,

  // Pontuações Histórico
  PONTUACAO_HISTORICO_CRESCIMENTO_ALTO: 30,
  PONTUACAO_HISTORICO_CRESCIMENTO_MEDIO: 25,
  PONTUACAO_HISTORICO_ESTAVEL: 20,
  PONTUACAO_HISTORICO_QUEDA_MEDIA: 10,
  PONTUACAO_HISTORICO_QUEDA_ALTA: 0,

  // Histórico de Incêndios
  INCENDIOS_NENHUM: 0,
  INCENDIOS_BAIXO: 3,
  INCENDIOS_MEDIO: 10,
  INCENDIOS_ALTO: 20,

  PONTUACAO_INCENDIOS_NENHUM: 20,
  PONTUACAO_INCENDIOS_BAIXO: 15,
  PONTUACAO_INCENDIOS_MEDIO: 10,
  PONTUACAO_INCENDIOS_ALTO: 5,
  PONTUACAO_INCENDIOS_CRITICO: 0,

  // Clima e Solo (Condições Ideais vs Críticas)
  CLIMA_UMIDADE_AR_IDEAL: 40,
  CLIMA_TEMP_IDEAL: 30,
  CLIMA_VENTO_IDEAL: 15,
  SOLO_UMIDADE_IDEAL: 0.1,

  CLIMA_UMIDADE_AR_CRITICO: 20,
  CLIMA_TEMP_CRITICA: 35,
  CLIMA_VENTO_CRITICO: 30,
  SOLO_UMIDADE_CRITICA: 0.05,

  PONTUACAO_CLIMA_BAIXO_RISCO: 5,
  PONTUACAO_CLIMA_MEDIO_RISCO: 3,
  PONTUACAO_CLIMA_ALTO_RISCO: 0,

  // Limiares de Classificação Geral
  CLASSIFICACAO_BAIXO_RISCO_MIN: 70,
  CLASSIFICACAO_ATENCAO_MIN: 40,
  LIMIAR_NDVI_DEGRADADO: 0.25,
  TETO_PONTUACAO_DEGRADADO: 35,
};
